### ISSUE TITLE
new tools

### ISSUE THREAD

**Issue by saberzaid** [som3canadian/Some-Tools#2]
hello 

please add https://github.com/Knowledge-Wisdom-Understanding/recon

its nice autorecon that cover and do recon based on the nmap result , tool is devloped also by one of the nmapautometor

**Comment by som3canadian** [comment]
Yes I will be happy to add it. I will post here when done.

Thanks for reaching out.

**Comment by som3canadian** [comment]
Sorry mate for the delay. I won't add it for the moment because the installation workflow is using opt folder (and not using variable), so it will be harder to keep track and won't be able to update those tools when using the update-all function. Will have to rewrite the setup.sh file. I may add it in the future. For the moment, I close the issue.
